# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/baseball-girl-web"

# 网页的标题
title: "棒球少女"
username: 海来金里-棒球少女成长日记
# 网站副标题
description: "棒球少女成长日记"

aboutme: "我是海来金里，棒球场上的小小牛魔王 ヾ(◍°∇°◍)ﾉﾞ "

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
